polaris:
  sync:
    registry:
      configWatchPath: ${POLARIS_SYNC_REGISTRY_CONFIG_WATCH_PATH:conf/sync-config.json}
      configBackupPath: ${POLARIS_SYNC_REGISTRY_CONFIG_BACKUP_PATH:conf/sync-config-backup.json}
logging:
  config: classpath:logback-sync.xml
  level:
    root: ${POLARIS_SYNC_LOGGER_LEVEL:info}
  path: ${POLARIS_SYNC_LOGGER_PATH:loggers}